[package]
name = "docdelve-qt-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
docdelve = { path = "../../lib" }
anyhow = "1.0"
regex = "1.10"
roxmltree = "0.19"
diffy = "0.3"
clap = { version = "4.4", features = ["derive"] }
