[package]
name = "docdelve-rust-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
docdelve = { path = "../../lib" }
anyhow = "1.0"
regex = "1.10"
scraper = "0.18"
clap = { version = "4.4", features = ["derive"] }
